### ISSUE TITLE
Update App to ensure compatibility with future reflex versions

### ISSUE THREAD

**Issue by dentroai** [tgberkeley/reflex-webcam#1]
When importing `import reflex_webcam as webcam` in reflex version 0.5.9 I get this warning:
```
DeprecationWarning: Creating a Var (muted) from a string without specifying _var_is_string has been deprecated in version 0.5.4 Specify 
_var_is_string=False to create a Var that is not a string literal. In the future, creating a Var from a string will be treated as a string 
literal by default. It will be completely removed in 0.6.0
```

Would be lovely if this could be fixed so that we can use reflex-webcam also using reflex 0.6.0 and forward!

**Comment by tgberkeley** [comment]
Yes we can definitely fix this by the time 0.6.0 comes out

**Comment by tgberkeley** [comment]
Fixed in latest version of the webcam (0.0.6)

**Comment by dentroai** [comment]
But on pypi there's still only version 0.0.5 https://pypi.org/project/reflex-webcam/

![image](https://github.com/user-attachments/assets/3619a912-4402-4b80-bee4-6fd5e94283a4)

**Comment by tgberkeley** [comment]
It is 0.0.6 on pypi
